# Generated by Django 5.0.6 on 2024-06-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blacklisted_tokens',
            field=models.TextField(blank=True),
        ),
    ]
