# Generated by Django 5.0.6 on 2024-06-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='profile_letters/default.png', upload_to='profile_pics/'),
        ),
    ]
