# Generated by Django 5.0.6 on 2024-06-08 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_customuser_blacklisted_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('token', models.TextField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Blacklisted Token',
                'verbose_name_plural': 'Custom Blacklisted Tokens',
            },
        ),
    ]
