# Generated by Django 5.0.6 on 2024-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='profile_letters/default.png', upload_to=''),
        ),
    ]
