# Generated by Django 5.0.6 on 2024-06-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_game_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
