# Generated by Django 5.0.6 on 2024-11-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_gameonline_platform_gameonline_html_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameonline',
            name='title_uri',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
