# Generated by Django 5.0.6 on 2024-11-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_gameonline_title_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameonline',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
